# Generated by Django 4.2.4 on 2023-08-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, verbose_name='Heading')),
                ('content', models.CharField(max_length=1000, verbose_name='Content')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='webapp.author')),
            ],
        ),
    ]
